{% set name = "trackintel" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trackintel-{{ version }}.tar.gz
  sha256: 484590e076bee854576e2ba986f69dae2c79a0a1b3fa20690ace1ae6430dd8c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - geopandas >=0.12.0
    - matplotlib-base
    - numpy
    - pint
    - networkx
    - geoalchemy2
    - osmnx
    - scikit-learn
    - tqdm
    - psycopg2
    - similaritymeasures

test:
  imports:
    - benchmarks
    - trackintel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mie-lab/trackintel
  summary: Human mobility and movement analysis framework.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hongyeehh
    - henrymartin1
    - NinaWie
