{% set name = "trackintel" %}
{% set version = "1.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trackintel-{{ version }}.tar.gz
  sha256: ab53d17f81d0fe8d6a1f5cee732cdd095700cc33d7ac4dc87374c269c8d8e7d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - geopandas >=0.9.0
    - matplotlib-base
    - numpy
    - pint
    - shapely
    - networkx >= 1.3.0
    - geoalchemy2
    - osmnx
    - scikit-learn
    - tqdm
    - similaritymeasures
    - pygeos >=0.10.0

test:
  imports:
    - benchmarks
    - trackintel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mie-lab/trackintel
  summary: Human mobility and movement analysis framework.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hong2223
