{% set name = "trackintel" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/trackintel-{{ version }}.tar.gz
  sha256: fbcefdc0421c7ff6e52b162946e1e9566c26fa5aeba0022414e77341836eeddd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - geopandas>=1.1.0
    - matplotlib-base
    - numpy
    - pint
    - networkx
    - geoalchemy2
    - osmnx>=2.0.0
    - scikit-learn
    - tqdm
    - psycopg2
    - similaritymeasures

test:
  imports:
    - benchmarks
    - trackintel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mie-lab/trackintel
  summary: Human mobility and movement analysis framework.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hongyeehh
    - henrymartin1
    - NinaWie
