{% set name = "trackintel" %}
{% set version = "1.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trackintel-{{ version }}.tar.gz
  sha256: 83d6df2fc3d9930a49e0c59fd54b6125c5e83d9b3900f67676c71693b3967008

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - geopandas >=0.9.0
    - matplotlib-base
    - numpy
    - pint
    - shapely
    - networkx
    - geoalchemy2
    - osmnx
    - scikit-learn
    - tqdm
    - similaritymeasures
    - pygeos >=0.10.0

test:
  imports:
    - benchmarks
    - trackintel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mie-lab/trackintel
  summary: Human mobility and movement analysis framework.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hong2223
